
name: CICD Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  Intergration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a linux command
        run: cat index.html


