
name: Testing
on:
  push:
    branches:
      - CICD

jobs:
  task-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a linux command
        run: cat index.html


